Fixed some blunders

diff --git a/src/qtbase-7-path.patch b/src/qtbase-7-path.patch
--- a/src/qtbase-7-path.patch
+++ b/src/qtbase-7-path.patch
@@ -71,3 +71,43 @@
  
  if __name__ == "__main__":
      parser = argparse.ArgumentParser()
+--- a/configure	2018-12-03 11:15:26.000000000 +0000
++++ b/configure	2019-06-14 09:44:15.015437041 +0000
+@@ -232,7 +232,7 @@
+ 
+     sdk=$(getSingleQMakeVariable "QMAKE_MAC_SDK" "$1")
+     if [ -z "$sdk" ]; then echo "QMAKE_MAC_SDK must be set when building on Mac" >&2; exit 1; fi
+-    sysroot=$(/usr/bin/xcrun --sdk $sdk --show-sdk-path 2>/dev/null)
++    sysroot=$(xcrun --sdk $sdk --show-sdk-path 2>/dev/null)
+     if [ -z "$sysroot" ]; then echo "Failed to resolve SDK path for '$sdk'" >&2; exit 1; fi
+ 
+     case "$sdk" in
+@@ -267,7 +267,7 @@
+                 # Prefix tool with toolchain path
+                 var=$(echo "$line" | cut -d '=' -f 1)
+                 val=$(echo "$line" | cut -d '=' -f 2-)
+-                sdk_val=$(/usr/bin/xcrun -sdk $sdk -find $(echo $val | cut -d ' ' -f 1))
++                sdk_val=$(xcrun -sdk $sdk -find $(echo $val | cut -d ' ' -f 1))
+                 val=$(echo $sdk_val $(echo $val | cut -s -d ' ' -f 2-))
+                 echo "$var=$val"
+             ;;
+@@ -318,7 +318,7 @@
+ #-------------------------------------------------------------------------------
+ 
+ if [ "$BUILD_ON_MAC" = "yes" ]; then
+-    if ! /usr/bin/xcode-select --print-path >/dev/null 2>&1; then
++    if ! xcode-select --print-path >/dev/null 2>&1; then
+         echo >&2
+         echo "   No Xcode selected. Please install Xcode via the App Store, " >&2
+         echo "   or the command line developer tools via xcode-select --install, " >&2
+@@ -329,8 +329,8 @@
+     fi
+ 
+     # In the else case we are probably using a Command Line Tools installation
+-    if /usr/bin/xcrun -find xcodebuild >/dev/null 2>&1; then
+-        if ! /usr/bin/xcrun xcodebuild -license check 2>/dev/null; then
++    if xcrun -find xcodebuild >/dev/null 2>&1; then
++        if ! xcrun xcodebuild -license check 2>/dev/null; then
+             echo >&2
+             echo "   Xcode setup not complete. You need to confirm the license" >&2
+             echo "   agreement by running 'sudo xcrun xcodebuild -license accept'." >&2
